config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  root 'pages#landing'

  get 'pages/landing', as: 'welcome'

  get '/pages/contact', to: 'pages#contact', as: 'contact'

  post '/pages/create', to: 'pages#create'

  get 'pages/faq', as: 'faq'

  get 'pages/settings', as: 'settings'

  get 'stripe/connect'

  get 'charges/thankyou'

  post 'charges', to: 'charges#create'

  resources :users, only: [:index]

  resources :profile, only: %i[index
                               edit
                               update
                               show
                               destroy]

  resources :conversations, only: %i[index
                                     show
                                     destroy] do

    collection do
      delete :empty_trash
    end

    member do
      post :restore
      post :reply
      post :mark_as_read
    end
  end

  resources :messages, only: %i[new
                                create]

  resources :commissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: %i[index empty_trash]
  before_action :get_box, only: [:index]

  def index
    @conversations = if @box.eql? 'inbox'
                       @mailbox.inbox
                     elsif @box.eql? 'sent'
                       @mailbox.sentbox
                     else
                       @mailbox.trash
                     end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
    @conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_box
    if params[:box].blank? || !%w[inbox sent trash].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :a, link_to(title.capitalize, conversations_path(box: title.downcase), opts)
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>

      <% if conversation.is_unread?(current_user) %>
        <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                    class: 'btn btn-xs btn-info', method: :post %>
      <% end %>
    <% end %>
  </div>

  <p><%= render 'conversations/participants', conversation: conversation %></p>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <span>
      <%= gravatar_for participant %>
      <%= participant.name %>
    </span>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<h2 class="text-white">Your Conversations</h2>
<div class="jumbotron">
    <nav class="nav nav-pills nav-justified nav-white">
        <%= mailbox_section 'inbox', @box, class: 'nav-item nav-link' %>
        <%= mailbox_section 'sent', @box, class: 'nav-item nav-link'  %>
        <%= mailbox_section 'trash', @box, class: 'nav-item nav-link'  %>
    </nav>

    <div class="col-sm-9 mx-auto my-4">
      <% if @box == 'trash' %>
        <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></p>
      <% end %>
      <ul class="list-group">
        <%= render partial: 'conversations/conversation', collection: @conversations %>
      </ul>

      <%= will_paginate %>
    </div>
  </div>

  <div class="container text-center my-4"><%= link_to 'Start conversation', new_message_path, class: 'btn btn-lg btn-primary' %></div>
</div>

app/views/conversations/show.html.erb
<h2 class="text-white">Conversation</h2>

<div class="text-white">
  <p>Chatting with
    <%= render 'conversations/participants', conversation: @conversation %>
  </p>

  <div class="panel panel-default">
    <div class="panel-heading display-4">
      <%= @conversation.subject %>
    </div>

    <div class="panel-body">
      <div class="messages container">
        <p><% @conversation.receipts_for(current_user).each do |receipt| %>
          <% message = receipt.message %>

          <p class="badge badge-pill badge-dark"><%= message.body %></p>
          <p class="font-weight-light">
          <%= message.sender.name %> -
          <%= message.created_at.strftime("%H:%M, %-d %b %Y" ) %>
          </p>
          <hr>
        <% end %>
      </p>
      </div>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>