config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  root 'pages#landing'

  get 'pages/landing', as: 'welcome'

  get '/pages/contact', to: 'pages#contact', as: 'contact'

  post '/pages/create', to: 'pages#create'

  get 'pages/faq', as: 'faq'

  get 'pages/settings', as: 'settings'

  get 'stripe/connect'

  get 'charges/thankyou'

  post 'charges', to: 'charges#create'

  resources :users, only: [:index]

  resources :profile, only: %i[index
                               edit
                               update
                               show
                               destroy]

  resources :conversations, only: %i[index
                                     show
                                     destroy] do

    collection do
      delete :empty_trash
    end

    member do
      post :restore
      post :reply
      post :mark_as_read
    end
  end

  resources :messages, only: %i[new
                                create]

  resources :commissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="text-white">
    <h3><%= pluralize(object.errors.count, "error") %> found:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<span>© Filip Maslovaric 2017</span><span><%= link_to 'Github', 'https://github.com/FilipMaslovaric/Develoo' %></span>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <%= link_to "Develoo", root_path, :class => "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= active_link_to "FAQ", faq_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "Contact Us", contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= active_link_to "Commissions", commissions_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.has_role? :admin %>
          <li class="nav-item">
            <%= active_link_to "Users", users_path, class: "nav-link" %>
          </li>
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav d-flex justify-content-between align-items-center">
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= gravatar_for current_user %>
            <%= current_user.name %> (<%= current_user.alias %>)
          </a>
          <div class="dropdown-menu align-items-center" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path(current_user), class: " dropdown-item" %>
            <%= link_to text_with_badge("Messages", current_user.unread_inbox_count), conversations_path, class: " dropdown-item" %>
            <%= link_to "Edit Account", edit_user_registration_path, class: " dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
          </div>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path , class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Sign up", new_user_registration_path , class: "nav-link" %>
        </li>
        <% end %>
      </ul>
  </div>
</nav>
<!-- <p><%= link_to "FAQ", faq_path %></p>
<p><%= link_to "Contact Us", contact_path %></p> -->