config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  root 'pages#landing'

  get 'pages/landing', as: 'welcome'

  get '/pages/contact', to: 'pages#contact', as: 'contact'

  post '/pages/create', to: 'pages#create'

  get 'pages/faq', as: 'faq'

  get 'pages/settings', as: 'settings'

  get 'stripe/connect'

  get 'charges/thankyou'

  post 'charges', to: 'charges#create'

  resources :users, only: [:index]

  resources :profile, only: %i[index
                               edit
                               update
                               show
                               destroy]

  resources :conversations, only: %i[index
                                     show
                                     destroy] do

    collection do
      delete :empty_trash
    end

    member do
      post :restore
      post :reply
      post :mark_as_read
    end
  end

  resources :messages, only: %i[new
                                create]

  resources :commissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_admins_list.html.erb
<div class="container-fluid text-center">
  <h4 class="text-white">Meet the Admins</h4>
  <div class="d-flex row">
    <% @profile.each do |profile| %>
      <% if profile.user.has_role? :admin %>
        <div class="mx-auto my-4">
          <div class="card" style="width: 20rem;">
            <%= gravatar_image_tag(profile.user.email, alt: profile.user.alias, class: "card-img-top", gravatar: { secure: true, default: :identicon, size: 310 } ) %>
            <div class="card-body">
              <h4 class="card-title"><%= profile.user.alias %></h4>
              <p class="card-text"></p>
              <%= link_to "Go to Profile", profile_path(profile) %>
            </div>
          </div>
        </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/pages/_devs_list.html.erb
<div class="container-fluid text-center">
  <h4 class="text-white">Meet the Devs</h4>
  <div class="d-flex row">
    <% @profile.each do |profile| %>
      <% if profile.user.has_role? :dev %>
        <div class="mx-auto my-4">
          <div class="card" style="width: 20rem;">
            <%= gravatar_image_tag(profile.user.email, alt: profile.user.alias, class: "card-img-top", gravatar: { secure: true, default: :identicon, size: 310 } ) %>
            <div class="card-body">
              <h4 class="card-title"><%= profile.user.alias %></h4>
              <p class="card-text"></p>
              <%= link_to "Go to Profile", profile_path(profile) %>
            </div>
          </div>
        </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/pages/contact.html.erb
<h2 class="text-white">Contact Us</h2>
<div class="jumbotron-fluid text-white">
  <h4>Questions? Concerns? Shoot us an e-mail</h4>

  <%= form_with(url: pages_create_url, local: true) do |form| %>

  <% if @errors.present? %>
    <div class="errors" >
      <% @errors.each do |error| %>
        <%= error %><br>
      <% end %>
    </div>
  <% end %>

  <hr>
    <div>
      <p><%= form.label 'Email: ' %></p>
      <p><%= form.email_field :email %></p>
    </div>
    <div>
      <p><%= form.label 'Message: ' %></p>
      <p><%= form.text_area :message %></p>
    </div>
    <div>
      <%= form.submit 'Submit', class: "btn btn-primary" %>
    </div>
  <hr>

  <% end %>
</div>

app/views/pages/faq.html.erb
<h2 class="text-white">Frequently Asked Questions</h2>

<ul class="text-white">
  <li>
    <h5>What is Develoo?</h5>
    <p>A marketplace where clients can commission web and software developers to make websites and applications directly, quickly and securely.</p>
  </li>
  <li>
    <h5>How does Develoo work if I'm a developer?</h5>
    <p> Devs set up their account and post what their skills are and what kind of work they are available to do by creating commissions.</p>
  </li>
  <li>
    <h5>How does Develoo work if I'm a client?</h5>
    <p>Clients search through the avialable commissions and once they find something that suits them, they can quickly hire the dev by purchasing the commission and then communicate directly through the website.</p>
  </li>
  <li>
    <h5>How do you handle payments?</h5>
    <p>Through Stripe. All payments are handled through a secure gateway and all devs have to be verified first before being able to make commissions.</p>
  </li>
  <li>
    <h5>Who is your mascot?</h5>
    <p>His name is 'Curly the Cuddlefish', and he was created on commission for Develoo by <%= link_to 'Gabriel Marinos', 'http://gabrielpmarinos.wix.com/folio', class: "text-warning" %>.</p>
  </li>
</ul>

app/views/pages/landing.html.erb
<div class="jumbotron-fluid">
  <div class="text-center">
    <%= image_tag("https://i.imgur.com/d3pBNA5.png", alt: "Curly the Cuddlefish", class: "img-fluid", height: 200, width: 200) %>
  </div>
  <h1 class="display-1 text-center text-white">Develoo</h1>
  <p class="small text-center text-white">Apps, built for you</p>
  <hr class="my-4" color="#111">
  <div class="container text-center text-white">
    <h5>Connect with Web and Software Developers and commission them to develop Websites and Apps for you.</h5>
    <h5>Ready to start?</h5>
    <%= link_to "Sign up!", new_user_registration_path , class: "btn btn-outline-info" %>
  </div>
</div>

<br>

<%= render "devs_list"%>
<hr>
<%= render "admins_list"%>

app/views/pages/settings.html.erb
<h2 class="text-white">Dev Settings</h2>

<p class="text-white"> Here you can edit your business details </p>

<h5 class="text-white"> Payment through Stripe</h5>
<% if @stripe_user_id.nil? %>
  <p class="text-warning">If you haven't already made an account with Stripe, click the link below to get started.</p>
  <a href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=<%= ENV.fetch('STRIPE_CLIENT_ID') %>&scope=read_write" class="stripe-connect btn btn-info mb-3"><span>Connect with Stripe</span></a>
  <div class="col-sm-12">
    <ul class="list text-bg-light">
      <li class="small text-info">You must have an account and associate it with Develoo in order to be able to make commissions and receive payment for them.</li>
      <li class="small text-info"> If you are seeing this and have already made an account with Stripe, and tried associating it with Develoo, an error might have occcured. If you believe this to be the case, please send a message to an admin on the site.</li>
    </ul>
  </div>
<% else %>
  <p class="text-success">Conected with Stripe! You are all set up, you can leave this page.</p>
<% end %>

app/views/pages/success.html.erb
<div class="jumbotron text-center">
  <h1 class="text-white">Success!</h1>
  <h4 class="text-success"> The support e-mail was sent</h4>
</div>