config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  root 'pages#landing'

  get 'pages/landing', as: 'welcome'

  get '/pages/contact', to: 'pages#contact', as: 'contact'

  post '/pages/create', to: 'pages#create'

  get 'pages/faq', as: 'faq'

  get 'pages/settings', as: 'settings'

  get 'stripe/connect'

  get 'charges/thankyou'

  post 'charges', to: 'charges#create'

  resources :users, only: [:index]

  resources :profile, only: %i[index
                               edit
                               update
                               show
                               destroy]

  resources :conversations, only: %i[index
                                     show
                                     destroy] do

    collection do
      delete :empty_trash
    end

    member do
      post :restore
      post :reply
      post :mark_as_read
    end
  end

  resources :messages, only: %i[new
                                create]

  resources :commissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/commission.rb
class Commission < ApplicationRecord
  belongs_to :user
  scope :active, -> { where(hidden: false) }
  mount_uploader :image, ImageUploader

  def self.search_by_description(search)
    if search
      where('description ILIKE ? AND hidden = false ', "%#{search}%")
    else
      active
    end
  end
end

app/controllers/commissions_controller.rb
class CommissionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_commission, only: %i[show edit update destroy]

  # GET /commissions
  # GET /commissions.json
  def index
    @commissions = Commission.active.order('created_at DESC')
    @commissions = Commission.search_by_description(params[:search])
  end

  # GET /commissions/1
  # GET /commissions/1.json
  def show; end

  # GET /commissions/new
  def new
    @commission = Commission.new
  end

  # GET /commissions/1/edit
  def edit; end

  # POST /commissions
  # POST /commissions.json
  def create
    @commission = Commission.new(commission_params)
    @commission.user = current_user

    respond_to do |format|
      if @commission.save
        format.html { redirect_to @commission, notice: 'Commission was successfully created.' }
        format.json { render :show, status: :created, location: @commission }
      else
        format.html { render :new }
        format.json { render json: @commission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commissions/1
  # PATCH/PUT /commissions/1.json
  def update
    respond_to do |format|
      if @commission.update(commission_params)
        format.html { redirect_to @commission, notice: 'Commission was successfully updated.' }
        format.json { render :show, status: :ok, location: @commission }
      else
        format.html { render :edit }
        format.json { render json: @commission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commissions/1
  # DELETE /commissions/1.json
  def destroy
    @commission.destroy
    respond_to do |format|
      format.html { redirect_to commissions_url, notice: 'Commission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_commission
    @commission = Commission.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def commission_params
    params.require(:commission).permit(:user_id, :title, :description, :price, :commission_id, :image, :remove_image)
  end
end

app/helpers/commissions_helper.rb
module CommissionsHelper
end

app/views/commissions/_commission_row.html.erb
<div class="card" style="width: 15rem;">
  <div class=card-img-top>
    <%= image_tag(commission.image.web.preview.url, alt: 'Image') if commission.image? %>
  </div>
  <div class="card-body">
    <h4 class="card-title"><%= link_to commission.title, commission, class: "card-link" %></h4>
    <div class="card-body text-left">
      <div class="card-text">
        Developed by <br><%= link_to commission.user.alias, profile_path(commission.user) %>
        <% if commission.user.profile.image? %>
          <%= link_to(image_tag(commission.user.profile.image.web.thumb.url, alt: 'Image', class: "img-fluid"), commission.user.profile.image.url, target: '_blank') %>
        <% else %>
          <%= gravatar_image_tag(commission.user.email, alt: commission.user.alias, class: "img-fluid", gravatar: { secure: true, default: :identicon, size: 32 }, href: commission ) %>
        <% end %>
      </div>
    </div>
    <hr>
    <div class="small">
      <%= commission.description %>
    </div>
    <p class="card-text text-center">
      <%= number_to_currency(commission.price) %>
    </p>
  </div>
  <div class="card-body">
      <% if user_signed_in? %>
        <% if current_user == commission.user or current_user.has_role? :admin %>
          <div class="card-body">
            <%= link_to 'Edit', edit_commission_path(commission), class: "btn btn-secondary" %>
            <%= link_to 'Destroy', commission, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link btn btn-danger" %>
          </div>
        <% end %>
    <% else %>
      <p class="card-text">Sign <span><%= link_to "in", new_user_session_path , class: "card-link" %></span>/<span><%= link_to "up", new_user_registration_path , class: "card-link" %></span> to see details</p>
    <% end %>
  </div>
</div>

app/views/commissions/_form.html.erb
<div class="text-white">
  <%= form_with(model: commission, local: true) do |form| %>
    <% if commission.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(commission.errors.count, "error") %> prohibited this commission from being saved:</h2>

        <ul>
        <% commission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.label :title %>
      <p class="small text-white">This is the first thing people will see</p>
      <%= form.text_field :title, id: :commission_title, class: "form-control col-sm-4", placeholder: "e.g. HTML5 Website..." %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <p class="small text-white">Give a brief description of the service you're offering. <br> Talk about your skills on your Profile instead.</p>
      <%= form.text_area :description, id: :commission_description, class: "form-control col-sm-4", placeholder: "e.g. HTML5 Single page static website..." %>
    </div>

    <div class="form-group">
      <%= form.label :image %>
      <p class="small text-white">Add a picture as an example</p>
      <p class="small text-white">Either upload a file directly</p>
      <% if commission.image? %>
        <%= image_tag commission.image.web.preview.url %>
        <div>
          <%= label_tag :remove_image do %>
            Remove image?
            <%= form.check_box :remove_image %>
          <% end %>
        </div>
      <% end %>
      <%= form.file_field :image, class: "form-control-file" %>
      <p class="small text-white my-1">Or</p>
      <%= form.text_field :remote_image_url, class: "form-control col-sm-4", placeholder: "Upload via URL" %>
    </div>

    <div class="form-group">
      <%= form.label :price %>
      <p class="small text-white">In dollars</p>
      <%= form.text_field :price, id: :commission_price, class: "form-control col-sm-4", placeholder: "e.g. 199.95" %>
    </div>

      <%= form.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/commissions/edit.html.erb
<% page_header "Editing Commission" %>

<%= render 'form', commission: @commission %>

<%= link_to 'Show', @commission %> |
<%= link_to 'Back', commissions_path %>

app/views/commissions/index.html.erb
<h2 class="text-white">Commissions</h2>

<div class="mb-2">
<% if user_signed_in? %>
  <% if current_user.has_any_role?(:admin, :dev) %>
    <% if current_user.stripe_user_id.nil? %>
      <h4 class="text-warning"> You must create a Stripe account before you can create and be paid for commissions </h4>
      <%= link_to "Set up your payment", 'pages/settings', class: "btn btn-outline-info" %>
    <% else %>
      <p><%= link_to 'New Commission', new_commission_path, class: "btn btn-primary" %></p>
    <% end %>
  <% end %>
<% end %>
</div>

<div class="form-inline">
<div class="form-group">
<%= form_tag commissions_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search], class: "form-control col-sm-12", placeholder: "Search commissions" %>
  <%= submit_tag "Search", class: "btn btn-primary span" %>
<% end %>
</div>
</div>

<div class="text-center my-4">
  <div class="card-group">
    <% @commissions.each do |commission| %>
      <%= render "commission_row", commission: commission %>
    <% end %>
  </div>
</div>

app/views/commissions/new.html.erb
<h2 class="text-white">Create New Commission</h2>

<%= render 'form', commission: @commission %>

<%= link_to 'Cancel', commissions_path, class: "btn btn-secondary my-4" %>

app/views/commissions/show.html.erb
<div class="text-white">
  <p>
    <%= image_tag(@commission.image.web.preview.url, alt: 'Image') if @commission.image? %>
  <p>
    <strong>Developer:</strong>
    <%= @commission.user.alias %>
  </p>

  <p>
    <strong>Commission:</strong>
    <%= @commission.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @commission.description %>
  </p>

  <hr>
  <div class="input-group d-flex justify-content-between">
      <% if user_signed_in? && current_user != @commission.user %>
        <div class="input-group-btn">
          <%= render 'charges/single_purchase' %>
        </div>
      <% end %>

    <h4 class="text-right">Price: <span class="text-warning"><%= number_to_currency(@commission.price) %></span></h4>
  </div>

  <div class=" btn-group my-2">
    <% if user_signed_in? %>
      <% if current_user == @commission.user or current_user.has_role? :admin %>
          <%= link_to 'Edit', edit_commission_path(@commission), class: "btn btn-small btn-secondary" %>
      <% end %>
    <% else %>
      <p class="small text-info mr-2">Please sign up or sign in to make a purchase</p>
    <% end %>
    <%= link_to 'Back', commissions_path, class: "btn btn-small btn-secondary" %>
  </div>
</div>